### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by dmytro-dubovets** [dmytro-dubovets/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by YuliaAwesome** [comment]
1970s - After college, works with his father on apartment complexes in Queens and Brooklyn.
1973 - Trump and his father are named in a Justice Department lawsuit alleging Trump property managers violated the Fair Housing Act by turning away potential African-American tenants. The Trumps deny the company discriminates and file a $100 million countersuit, which is later dismissed. The case is settled in 1975, and the Trumps agree to provide weekly lists of vacancies to black community organizations.
1976 - Trump and his father partner with the Hyatt Corporation, purchasing the Commodore Hotel, an aging midtown Manhattan property. The building is revamped and opens four years later as the Grand Hyatt Hotel. The project kickstarts Trump's career as a Manhattan developer.
1983-1990 - He builds/purchases multiple properties in New York City, including Trump Tower and the Plaza Hotel, and also opens casinos in Atlantic City, New Jersey, including the Trump Taj Mahal and the Trump Plaza. Trump buys the New Jersey Generals football team, part of the United States Football League, which folds after three seasons.
1985 - Purchases Mar-a-Lago, an oceanfront estate in Palm Beach, Florida. It is renovated and opens as a private club in 1995.
1987 - Trump's first book, "Trump: The Art of the Deal," is published and becomes a bestseller. The Donald J. Trump Foundation is established in order to donate a portion of profits from book sales to charities.
1990 - Nearly $1 billion in personal debt, Trump reaches an agreement with bankers allowing him to avoid declaring personal bankruptcy.
1991 - The Trump Taj Mahal files for Chapter 11 bankruptcy protection.
1992 - The Trump Plaza and the Trump Castle casinos file for bankruptcy.
1996 - Buys out and becomes executive producer of the Miss Universe, Miss USA and Miss Teen USA pageants.
October 7, 1999 - Tells CNN's Larry King that he is going to form a presidential exploratory committee and wants to challenge Pat Buchanan for the Reform Party nomination.
February 14, 2000 - Says that he is abandoning his bid for the presidency, blaming discord within the Reform Party.
January 2004 - "The Apprentice," a reality show featuring aspiring entrepreneurs competing for Trump's approval, premieres on NBC.
November 21, 2004 - Trump Hotels & Casino Resorts Inc. files for Chapter 11 bankruptcy.
2005 - Establishes Trump University, which offers seminars in real estate investment.
February 13, 2009 - Announces his resignation from his position as chairman of Trump Entertainment Resorts. Days later, the company files for bankruptcy protection.
March 17, 2011 - During an interview on ABC's "Good Morning America," Trump questions whether President Barack Obama was born in the United States.
June 16, 2015 - Announces that he is running for president during a speech at Trump Tower. He pledges to implement policies that will boost the economy and says he will get tough on immigration. "When Mexico sends its people, they're not sending their best...They're sending people who have lots of problems," Trump says. "They're bringing drugs, they're bringing crime, they're rapists, and some, I assume, are good people."
June 28, 2015 - Says he's giving up the TV show "The Apprentice" to run for president.
June 29, 2015 - NBCUniversal says it is cutting its business ties to Trump and won't air the Miss USA and Miss Universe pageants because of "derogatory statements by Donald Trump regarding immigrants."
July 8, 2015 - In an interview with CNN's Anderson Cooper, Trump says he "can't guarantee" all of his employees have legal status in the United States. This is in response to questions about a Washington Post report about undocumented immigrants working at the Old Post Office construction site in Washington, which Trump is converting into a hotel.
July 22, 2015 - Trump's financial disclosure report is made public by the Federal Election Commission.
August 6, 2015 - During the first 2016 Republican debate, Trump is questioned about a third party candidacy, his attitude towards women and his history of donating money to Democratic politicians. He tells moderator Megyn Kelly of Fox News he feels he is being mistreated.
August 7, 2015 - The controversy continues, as Trump tells CNN's Don Lemon that Kelly was singling him out for attack, "You could see there was blood coming out of her eyes, blood coming out of her wherever."
September 11, 2015 - Trump announces he has purchased NBC's half of the Miss Universe Organization, which organizes the annual Miss USA and Miss Universe pageants.
December 7, 2015 - Trump's campaign puts out a press release calling for a "complete shutdown of Muslims entering the United States until our country's representatives can figure out what is going on."
May 26, 2016 - Secures enough delegates to clinch the Republican Party nomination.
July 16, 2016 - Introduces Indiana Governor Mike Pence as his running mate.
July 19, 2016 - Becomes the Republican Party nominee for president.
September 13, 2016 - During an interview with CNN's Jake Tapper, New York Attorney General Eric Schneiderman says his office is investigating Trump's charitable foundation "to make sure it's complying with the laws governing charities in New York."
October 1, 2016 - The New York Times reports Trump declared a $916 million loss in 1995 which could have allowed him to legally skip paying federal income taxes for years. The report is based on a financial document mailed to the newspaper by an anonymous source.
October 7, 2016 - Unaired footage from 2005 surfaces of Trump talking about trying to have sex with a married woman and being able to grope women. In footage obtained by The Washington Post, Trump is heard off-camera discussing women in vulgar terms during the taping of a segment for "Access Hollywood." In a taped response, Trump declares, "I said it, I was wrong and I apologize."
October 9, 2016 - During the second presidential debate, CNN's Cooper asks Trump about his descriptions of groping and kissing women without their consent in the "Access Hollywood" footage. Trump denies that he has ever engaged in such behavior and declares the comments were "locker room talk." After the debate, 11 women step forward to claim that they were sexually harassed or sexually assaulted by the real estate developer. Trump says the stories aren't true.
November 8, 2016 - Is elected president of the United States. Trump will be the first president who has never held elected office, a top government post or a military rank.
November 18, 2016 - Trump agrees to pay $25 million to settle three lawsuits against Trump University. The deal keeps the President-elect from having to testify in a trial in San Diego that was set to begin November 28. The settlement ends a suit brought by Schneiderman, as well as two class action suits in California. About 6,000 former students are covered by the settlement.
December 24, 2016 - Trump says he will dissolve the Donald J. Trump Foundation "to avoid even the appearance of any conflict with my role as President." A spokeswoman for the New York Attorney General's Office says that the foundation cannot legally close until investigators conclude their probe of the charity.
January 10, 2017 - CNN reports that intelligence officials briefed Trump on a dossier that contains allegations about his campaign's ties to Russia and unverified claims about his personal life. The author of the dossier is a former British spy who was hired by a research firm that had been funded by both political parties to conduct opposition research on Trump.
January 20, 2017 - Takes the oath of office from Chief Justice John Roberts during an inauguration ceremony at the Capitol and delivers an inaugural address centering on the populist themes that fueled his candidacy.
January 23, 2017 - Trump signs an executive action withdrawing the United States from the Trans-Pacific Partnership, a 12-nation trade deal negotiated by the Obama administration and awaiting congressional approval.
January 27, 2017 - Trump signs an executive order halting all refugee arrivals for 120 days and banning travel to the United States from seven Muslim-majority countries for 90 days. Additionally, refugees from Syria are barred indefinitely from entering the United States. The order is challenged in court.
February 13, 2017 - Trump's national security adviser, Michael Flynn, resigns amid accusations he lied about his communications with Russian ambassador to the United States, Sergey Kislyak. Flynn later pleads guilty to lying to the FBI.
February 28, 2017 - Nominates Neil Gorsuch to replace late Supreme Court Justice Antonin Scalia.
May 3, 2017 - FBI Director James Comey confirms that there is an ongoing investigation into ties between the Trump campaign and Russia during a hearing on Capitol Hill. Less than a week later, Trump fires Comey, citing a DOJ memo critical of the way he handled the investigation into Clinton's emails.
May 2017 - Shortly after Trump fired Comey, the FBI opens an investigation into whether Trump "had been working on behalf of Russia against American interests," citing former law enforcement officials and others the paper said were familiar with the probe.
May 17, 2017 - Former FBI Director Robert Mueller is appointed as special counsel to lead the probe into Russian meddling in the 2016 election, including potential collusion between Trump campaign associates and Russian officials. Deputy Attorney General Rod Rosenstein makes the appointment because Attorney General Jeff Sessions recused himself in March from investigations into Trump's campaign.
May 19, 2017 - Departs on his first foreign trip as president. The nine-day, five-country trip includes stops in Saudi Arabia, Israel, the Vatican, a NATO summit in Brussels and a G7 summit in Sicily.
June 1, 2017 - Trump proclaims that the United States is withdrawing from the Paris climate accord but adds that he is open to renegotiating aspects of the environmental agreement, which was signed by 175 countries in 2016.
July 7, 2017 - Meets Russian President Vladimir Putin in person for the first time, on the sidelines of the G20 meeting in Hamburg, Germany.
August 8, 2017 - In response to nuclear threats from North Korea, Trump warns that Pyongyang will "face fire and fury like the world has never seen." Soon after Trump's comments, North Korea issues a statement saying it is "examining the operational plan" to strike areas around the US territory of Guam.
August 15, 2017 - After a violent clash between neo-Nazi activists and counterprotesters leaves one dead in Charlottesville, Virginia, Trump holds an impromptu press conference in the lobby of Trump Tower and declares that there were "fine people" on both sides.
August 25, 2017 - Trump's first pardon is granted to former Arizona sheriff Joe Arpaio, who was convicted of criminal contempt for disregarding a court order in a racial-profiling case. Trump did not consult with lawyers at the Justice Department before announcing his decision.
September 5, 2017 - The Trump administration announces that it is ending the DACA program, introduced by Obama to protect nearly 800,000 undocumented immigrants brought to the United States as children. Trump calls on Congress to introduce legislation that will prevent DACA recipients from being deported. Multiple lawsuits are filed opposing the policy in federal courts and judges delay the end of the program, asking the government to submit filings justifying the cancellation of DACA.
September 19, 2017 - In a speech at the United Nations General Assembly, Trump refers to North Korean leader Kim Jong Un as "Rocket Man" and warns that the United States will "totally destroy North Korea" if forced to defend itself or its allies.
September 24, 2017 - The Trump administration unveils a third version of the travel ban, placing restrictions on travel by certain foreigners from Chad, Iran, Libya, North Korea, Somalia, Syria, Venezuela and Yemen. (Chad is later removed after meeting security requirements.) One day before the revised ban is set to take effect, it is blocked nationwide by a federal judge in Hawaii. A judge in Maryland issues a similar ruling.
December 4, 2017 - The Supreme Court rules that the revised travel ban can take effect pending appeals.
December 6, 2017 - Trump recognizes Jerusalem as Israel's capital and announces plans to relocate the US Embassy there.
January 11, 2018 - During a White House meeting on immigration reform, Trump reportedly refers to Haiti and African nations as "shithole countries." He reportedly says that the United States should get more people from countries like Norway.
January 12, 2018 - The Wall Street Journal reports that Trump had an alleged affair with a porn star named Stephanie Clifford, aka Stormy Daniels. The newspaper states that Trump's personal attorney, Michael Cohen, arranged a $130,000 payment for a nondisclosure agreement weeks before Election Day in 2016. Cohen denies that Trump had a relationship with Clifford.
March 13, 2018 - Trump announces in a tweet that he has fired Secretary of State Rex Tillerson and will nominate CIA Director Mike Pompeo as Tillerson's replacement.
March 20, 2018 - A New York Supreme Court judge rules that a defamation lawsuit against Trump can move forward, ruling against a July 2017 motion to dismiss filed by Trump's lawyers. The lawsuit, filed by Summer Zervos, a former "Apprentice" contestant, is related to sexual assault allegations.
March 23, 2018 - The White House announces that it is adopting a policy, first proposed by Trump via tweet in July 2017, banning most transgender individuals from serving in the military.
April 9, 2018 - The FBI raids Cohen's office, home and a hotel room where he'd been staying while his house was renovated. The raid is related to a federal investigation of possible fraud and campaign finance violations.
April 13, 2018 - Trump authorizes joint military strikes in Syria with the UK and France after reports the government used chemical weapons on civilians in Douma.
May 7, 2018 - The Trump administration announces a "zero tolerance" policy for illegal border crossings. Sessions says that individuals who violate immigration law will be criminally prosecuted and warns that parents could be separated from children.
May 8, 2018 - Trump announces that the United States is withdrawing from the Iran nuclear deal. "This was a horrible one-sided deal that should have never, ever been made," he says in remarks that, at times, misrepresent the international agreement's provisions.
May 31, 2018 - The Trump administration announces it is imposing tariffs on steel and aluminum imported from allies Canada, Mexico and the European Union.
June 8-9, 2018 - Before leaving for the G7 summit in Quebec City, Trump tells reporters that Russia should be reinstated in the group. The annexation of Crimea in 2014 led to Russia's suspension. After leaving the summit, Trump tweets that he will not endorse the traditional G7 communique issued at the end of the meeting. The President singles out Canadian Prime Minister Justin Trudeau for making "false statements" at a news conference.
June 12, 2018 - Trump meets Kim in person for the first time during a summit in Singapore. They sign a four-point statement that broadly outlines the countries' commitment to a peace process. The statement contains a pledge by North Korea to "work towards" complete denuclearization but the agreement does not detail how the international community will verify that Kim is ending his nuclear program.
June 14, 2018 - The New York attorney general sues the Trump Foundation, alleging that the nonprofit run by Trump and his three eldest children violated state and federal charity law.
June 26, 2018 - The Supreme Court upholds the Trump administration's travel ban in a 5-4 ruling along party lines.
July 16, 2018 - During a joint news conference with Putin in Helsinki, Trump declines to endorse the US government's assessment that Russia interfered in the election, saying he doesn't "see any reason why" Russia would be responsible. The next day, Trump clarifies his remark, "The sentence should have been, 'I don't see any reason why it wouldn't be Russia." He says he accepts the intelligence community's conclusion that Russia meddled in the election but adds, "It could be other people also."
August 21, 2018 - Cohen pleads guilty to eight federal charges, including two campaign finance violations. In court, he says that he orchestrated payments to silence women "in coordination and at the direction of a candidate for federal office." On the same day, Trump's former campaign chairman, Paul Manafort is convicted on eight counts of federal financial crimes. On December 12 Cohen is sentenced to three years in prison.
October 2, 2018 - The New York Times details numerous tax avoidance schemes allegedly carried out by Trump and his siblings. In a tweet, Trump dismisses the article as a "very old, boring and often told hit piece."
November 20, 2018 - Releases a statement backing Saudi Arabia in the wake of the murder of Washington Post journalist Jamal Khashoggi, a Virginia resident, killed in October at a Saudi consulate in Turkey. Khashoggi was a frequent critic of the Saudi regime. The Saudis initially denied any knowledge of his death, but then later said a group of rogue operators were responsible for his killing. US officials have speculated that such a mission, including the 15 men sent from Riyadh, Saudi Arabia, to murder him, could not have been carried out without the authorization of Saudi leader Crown Prince Mohammed bin Salman. In the statement, Trump writes, "Our intelligence agencies continue to assess all information, but it could very well be that the Crown Prince had knowledge of this tragic event, maybe he did and maybe he didn't!"
December 18, 2018 - The Donald J. Trump Foundation agrees to dissolve according to a document filed in Manhattan Supreme Court. The agreement allows the New York attorney general's office to review the recipients of the charity's assets.
December 19, 2018 - Trump declares that the United States has defeated ISIS and orders a "full" and "rapid" withdrawal of US military from Syria.
December 20, 2018 - Secretary of Defense James Mattis resigns in the wake of the Syria announcement, submitting a resignation letter that says "Because you have the right to have a Secretary of Defense whose views are better aligned with yours on these and other subjects, I believe it is right for me to step down from my position."
December 22, 2018 - The longest partial government shutdown in US history begins after Trump demands lawmakers allocate $5.7 billion in funding for a border wall before agreeing to sign a federal funding package.
January 16, 2019 - After nearly two years of Trump administration officials denying that anyone involved in his campaign colluded with the Russians to help his candidacy, Trump lawyer and former New York City mayor, Rudy Giuliani, says "I never said there was no collusion between the campaign, or people in the campaign. I said the President of the United States. There is not a single bit of evidence the President of the United States committed the only crime you can commit here, conspiring with the Russians to hack the DNC."
January 25, 2019 - The government shutdown ends when Trump signs a short-term spending measure, providing three weeks of stopgap funding while lawmakers work on a border security compromise. The bill does not include any wall funding.
February 15, 2019 - Trump declares a national emergency to allocate funds to build a wall on the border with Mexico. During the announcement, the President says he expects the declaration to be challenged in court. The same day, Trump signs a border security measure negotiated by Congress, with $1.375 billion set aside for barriers, averting another government shutdown.
February 18, 2019 - Attorneys general from 16 states file a lawsuit in federal court challenging Trump's emergency declaration.
March 22, 2019 - Mueller ends his investigation and delivers his report to Attorney General William Barr. A senior Justice Department official tells CNN that there will be no further indictments.
March 24, 2019 - Barr releases a letter summarizing the principal conclusions from Mueller's investigation. According to Barr's four-page letter, the evidence was not sufficient to establish that members Trump's campaign tacitly engaged in a criminal conspiracy with the Russian government to interfere with the election.
April 18, 2019 - A redacted version of the Mueller report is released. The first part of the 448-page document details the evidence gathered by Mueller's team on potential conspiracy crimes and explains their decisions not to charge individuals associated with the campaign. The second part of the report outlines ten episodes involving possible obstruction of justice by the President. According to the report, Mueller's decision not to charge Trump was rooted in Justice Department guidelines prohibiting the indictment of a sitting president. Mueller writes that he would have cleared Trump if the evidence warranted exoneration."If we had confidence after a thorough investigation of the facts that the President clearly did not commit obstruction of justice, we would so state," Mueller writes. "Based on the facts and the applicable legal standards, however, we are unable to reach that judgment."
May 1, 2019 - The New York Times publishes a report that details how Giuliani, in his role as Trump's personal attorney, is investigating allegations related to former Vice President Joe Biden, a potential Trump opponent in the 2020 presidential race. Biden's son, Hunter Biden served on the board of a Ukrainian energy company called Burisma Holdings. In 2016, the elder Biden pressured Ukraine to oust a prosecutor who had investigated Burisma for corruption. Giuliani suggests that Biden's move was motivated by a desire to protect his son from criminal charges. Giuliani's claims are undermined after Bloomberg reports that the Burisma investigation was "dormant" when Biden pressed the prosecutor to resign.
June 12, 2019 - Trump says he may be willing to accept information about political rivals from a foreign government during an interview on ABC News, declaring that he's willing to listen and wouldn't necessarily call the FBI.
June 16, 2019 - Israeli Prime Minister Benjamin Netanyahu unveils a sign at the proposed site of a Golan Heights settlement to be named Trump Heights.
June 18, 2019 - Trump holds a rally in Orlando to publicize the formal launch of his reelection campaign.
June 21, 2019 - In a series of tweets, Trump explains that he canceled a retaliatory attack on Iran in response to an American drone getting shot down. The President writes that he called off the strike after being told that 150 people could have been killed, reasoning that the response was not proportional since the downed American aircraft was unmanned.
June 28, 2019 - During a breakfast meeting at the G20 summit in Osaka, Japan, Trump and Saudi Crown Prince Mohamed bin Salman reportedly discuss tensions with Iran, trade and human rights.
June 30, 2019 - Trump becomes the first sitting US president to enter North Korea. He takes 20 steps beyond the border and shakes hands with Kim, the leader of the hermit kingdom. Although the American and North Korean governments tout the historic nature of the meeting, their talks do not appear to have yielded any new commitments to denuclearization.
July 14, 2019 - Via Twitter, Trump tells Reps. Alexandria Ocasio-Cortez, Rashida Tlaib, Illhan Omar and Ayanna Pressley to "go back" to their home countries. Ocasio-Cortez, Tlaib and Pressley are natural-born US citizens; Omar was born in Somalia, immigrated to the United States and became a citizen.
July 16, 2019 - The House votes, 240-187, to condemn the racist language Trump used in his tweets about Ocasio-Cortez, Tlaib, Omar and Pressley.
July 24, 2019 - Mueller testifies before the House Judiciary Committee and the House Intelligence Committee.
July 25, 2019 - Trump speaks on the phone with Ukrainian President Volodymyr Zelensky. Trump asks Zelensky for a "favor," encouraging him to speak with Giuliani about investigating Biden. In the days before the call, Trump blocked nearly $400 million in military and security aid to Ukraine.
July 27, 2019 - Trump rails against Democratic Rep. Elijah Cummings on Twitter, describing the Baltimore lawmaker's district as a "rat and rodent infested mess."
August 7, 2019 - In the wake of two separate mass shootings, Trump visits first responders and victims in El Paso, Texas, and Dayton, Ohio.
August 12, 2019 - A whistleblower files a complaint pertaining to Trump's conduct on the Zelensky call.
August 29, 2019 - Trump announces the establishment of the Space Command, a military unit that will oversee security of satellites.
September 10, 2019 - House Intelligence Committee Chairman Adam Schiff (D-CA) sends a letter to Joseph Maguire, acting Director of National Intelligence. Schiff demands that Maguire share the whistleblower complaint with Congress.
September 11, 2019 - The Trump administration lifts its hold on military aid for Ukraine.
September 18, 2019 - Schiff announces that Maguire has agreed to testify before the Intelligence Committee.
September 24, 2019 - House Speaker Nancy Pelosi announces the beginning of an impeachment inquiry related to the whistleblower complaint.
September 25, 2019 - The White House releases notes from the July 25 call between Trump and Zelensky. The readout contains multiple references to Giuliani and Barr. In response, the Justice Department issues a statement that says Barr didn't know about Trump's conversation until weeks after the call. Further, the attorney general didn't talk to the President about having Ukraine investigate the Bidens, according to the Justice Department. On the same day as the notes are released,Trump and Zelensky meet in person for the first time on the sidelines of the UN General Assembly. During a joint press conference after the meeting, both men deny that Trump pressured Zelensky to investigate Biden in exchange for aid. Trump says the notes from the call exonerate him: "Impeachment for What? When you have a wonderful meeting or you have a wonderful phone conversation?"
September 26, 2019 - The House releases a declassified version of the whistleblower complaint just before a hearing with Maguire. According to the complaint, officials at the White House tried to "lock down" records of Trump's phone conversation with Zelensky. The complaint also alleges that Barr played a role in the campaign to convince Zelensky that Biden should be investigated. Trump describes the complaint as "fake news" and "a witch hunt" on Twitter.
September 27, 2019 - Pompeo is subpoenaed by House committees over his failure to provide documents related to Ukraine. Kurt Volker, US special envoy to Ukraine, resigns. He was named in the whistleblower complaint as one of the State Department officials who helped Giuliani connect with sources in Ukraine.
October 3, 2019 - Speaking to reporters outside the White House, Trump says both Ukraine and China should investigate alleged corruption involving Biden and his son. CNN reports that the President had brought up Biden and his family during a June phone call with Xi Jinping. In that call, Trump discussed the political prospects of Biden as well as Elizabeth Warren. He also told Xi that he would remain quiet on the matter of Hong Kong protests. Notes documenting the conversation were placed on a highly secured server where the transcript from the Ukraine call was also stored.
October 6, 2019 - After Trump speaks on the phone with Turkish President Recep Tayyip Erdogan, the White House announces that US troops will move out of northern Syria to make way for a planned Turkish military operation. The move marks a major shift in American foreign policy and effectively gives Turkey the green light to attack US-backed Kurdish forces, a partner in the fight against ISIS.
October 9, 2019 - Turkey launches a military offensive in northern Syria.
October 31, 2019 - Trump says via Twitter that he is changing his legal residency from New York to Florida, explaining that he feels he is treated badly by political leaders from the city and state.
November 7, 2019 - A judge orders Trump to pay $2 million to settle a lawsuit against his charity filed by the New York state attorney general. According to the suit, Trump breached his fiduciary duty by allowing his presidential campaign to direct the distribution of donations. In a statement, Trump accuses the attorney general of mischaracterizing the settlement for political purposes.
November 13, 2019 - Public impeachment hearings begin and Trump meets Erdogan at the White House.
November 20, 2019 - During a public hearing, US Ambassador to the European Union Gordon Sondland says he worked with Giuliani on matters related to Ukraine at the "express direction of the President of the United States" and he says "everyone was in the loop." Sondland recounts several conversations between himself and Trump about Ukraine opening two investigations: one into Burisma and another into conspiracies about Ukrainian meddling in the 2016 US election.
December 10, 2019 - House Democrats unveil two articles of impeachment, one for abuse of power and one for obstruction of Congress. In response to the articles, House Minority Leader Kevin McCarthy says, "It is not difficult to defend this President because this President did nothing that is impeachable."
December 11, 2019 - Trump signs an executive order to include discrimination against Jewish people as a violation of law in certain cases, with an eye toward fighting anti-Semitism on college campuses.
December 13, 2019 - The House Judiciary Committee approves the two articles of impeachment in a party line vote, setting the stage for a vote on the floor of the House.
December 18, 2019 - The House of Representatives votes to impeach Trump, charging a president with high crimes and misdemeanors for just the third time in American history.
January 3, 2020 - Speaking at Mar-a-Lago, Trump announces that a US airstrike in Iraq has killed Qasem Soleimani, the leader of the Islamic Revolutionary Guards Corps Quds Force. "We took action last night to stop a war. We did not take action to start a war," Trump says. During an evangelical event later in the day, Trump says that Soleimani was planning a major attack, though the administration does not provide evidence of the intelligence.
January 8, 2020 - Iran fires a number of missiles at two Iraqi bases housing US troops in retaliation for the American strike that killed Soleimani. No US or Iraqi lives are reported lost, but the Pentagon later releases a statement confirming that 109 US service members had been diagnosed with mild traumatic brain injuries in the wake of the attack.
January 15, 2020 - Signs an initial trade deal with senior Chinese leaders that includes pledges from Beijing to more than double its purchases from American farmers in the first year.
January 24, 2020 - Makes history as the first President to attend the annual March for Life rally in Washington since it began nearly a half-century ago. Trump reiterates his support for tighter abortion restrictions, pledging that "unborn children have never had a stronger defender in the White House."
January 29, 2020 - Trump signs the US-Mexico-Canada Agreement into law, which replaces the North American Free Trade Agreement.

January 31, 2020 - The Trump administration announces an expansion of the travel ban -- which has been derided by critics as an attempt to ban Muslims from the United States -- to include six new countries. Immigration restrictions will be imposed on: Nigeria, Eritrea, Tanzania, Sudan, Kyrgyzstan and Myanmar (known as Burma), with exceptions for immigrants who have helped the United States.
February 5, 2020 - The Senate votes to acquit Trump on two articles of impeachment. Sen Mitt Romney is the sole Republican to vote to convict on the charge of abuse of power, joining with all Senate Democrats in a 52-48 not guilty vote. On the obstruction of Congress charge, the vote falls along straight party lines, 53-47 for acquittal.
